# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 6.0.2 on 2026-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="is_published",
        ),
        migrations.AddField(
            model_name="announcement",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата-время публикации"
            ),
        ),
    ]
