# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 6.0.1 on 2026-01-24 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Доступен ли курс пользователям",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(verbose_name="Порядок урока в курсе"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_lessons",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_courses",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок курса",
                "verbose_name_plural": "Уроки курса",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                through="courses.CourseLesson",
                to="lessons.lesson",
                verbose_name="Уроки",
            ),
        ),
        migrations.AddConstraint(
            model_name="courselesson",
            constraint=models.UniqueConstraint(
                fields=("course", "lesson"), name="unique_course_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="courselesson",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_course_order"
            ),
        ),
    ]
