# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 6.0.1 on 2026-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Доступен ли курс пользователям",
                verbose_name="Опубликован",
            ),
        ),
    ]
