# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 6.0.4 on 2026-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chords", "0002_alter_chordposition_finger_alter_chordposition_fret"),
    ]

    operations = [
        migrations.AddField(
            model_name="chord",
            name="svg_horizontal",
            field=models.TextField(
                blank=True, default="", verbose_name="SVG горизонтальный"
            ),
        ),
        migrations.AddField(
            model_name="chord",
            name="svg_vertical",
            field=models.TextField(
                blank=True, default="", verbose_name="SVG вертикальный"
            ),
        ),
    ]
