# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.8 on 2026-01-11 19:05

import markdownx.models # type: ignore[import-untyped]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chords", "0002_alter_chordposition_finger_alter_chordposition_fret"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "text",
                    markdownx.models.MarkdownxField(
                        help_text="С аккордами и переносами строк",
                        verbose_name="Текст песни",
                    ),
                ),
                ("metronome", models.IntegerField(default=0, verbose_name="Метроном")),
                (
                    "chords",
                    models.ManyToManyField(
                        blank=True, to="chords.chord", verbose_name="Аккорды"
                    ),
                ),
                (
                    "schemes",
                    models.ManyToManyField(
                        blank=True,
                        to="schemes.imagescheme",
                        verbose_name="Ритмические рисунки (изображения)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Песня",
                "verbose_name_plural": "Песни",
            },
        ),
    ]
