# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 6.0.5 on 2026-05-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_add_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
