# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.8 on 2026-01-23 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание содержания урока",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Ссылка на видео урока", verbose_name="Видео"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Общая длительность урока в секундах",
                        verbose_name="Длительность (сек)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "addition_lessons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommended_for",
                        to="lessons.lesson",
                        verbose_name="Рекомендуемые дополнительные уроки",
                    ),
                ),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Песни, которые разбираются в уроке",
                        related_name="lessons",
                        to="songs.song",
                        verbose_name="Песни",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
